### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Kasanias** [Kasanias/Numeriweb#2]
- [x] Creating Tab Component for Desktop
- [x] Add navigation icons in Tab Desktop
- [x] Remove keyboard auto completion
- [x] Adding long tap on resource to display more informations

**Comment by Kasanias** [comment]
For tabs:
-> Add transition directly on code
-> Redo a tab component
